localstack:
  stages:
    # list of stages for which the plugin should be enabled
    - local
  host: http://localhost  # optional - LocalStack host to connect to
  autostart: true  # optional - start LocalStack in Docker on Serverless deploy
  endpoints:
    # This section is optional - can be used for customizing the target endpoints
    CloudFormation: http://localhost:4581
    SNS: http://localhost:4575
    Lambda: http://localhost:4574
  lambda:
    # Enable this flag to improve performance
    mountCode: True
  docker:
    # Enable this flag to run "docker ..." commands as sudo
    sudo: False

stages:
  - local
  - production